-- Auto-generated from Alojamientos_convertido.xlsx
-- 346 accommodations along the Camino Portugues
-- Idempotent: safe to re-run (upsert on external_code)

INSERT INTO accommodations (external_code, name, address, stage_name, town, active)
VALUES
  ('1.01', 'CASA PASAXE', 'Avenida Paseo Portugal, 71, 36780 A Guarda, Pontevedra', 'A Guarda', 'A Guarda', true),
  ('1.02', 'Casa Leira Braulia', 'Rúa Outeiro, 39, 36788 Camposancos, Pontevedra', 'A Guarda', 'A Guarda', true),
  ('1.03', 'Hotel Bruselas', 'Rúa Ourense, 7, 36780 A Guarda, Pontevedra', 'A Guarda', 'A Guarda', true),
  ('1.04', 'Hotel Vila da Guarda', 'Rúa Tomiño, 8, 36789 A Guarda, Pontevedra', 'A Guarda', 'A Guarda', true),
  ('1.05', 'Hotel GBC Celta', 'Rúa Galicia, 53, 36780 A Guarda, Pontevedra', 'A Guarda', 'A Guarda', true),
  ('1.06', 'Hotel Eli-mar', 'Rúa Vicente Sobrino, 12, 36780 A Guarda, Pontevedra', 'A Guarda', 'A Guarda', true),
  ('1.07', 'Albergue de peregrinos de A Guarda', 'Rúa Puerto Rico, 7, 36780 A Guarda, Pontevedra', 'A Guarda', 'A guarda', true),
  ('1.08', 'Albergue O Peirao', 'Rúa Oliva, 43, 36780 A Guarda, Pontevedra', 'A Guarda', 'A Guarda', true),
  ('1.09', 'Arena Grande Hotel', 'Rúa Baixada á Praia, s/n, 36789 A Guarda, Pontevedra', 'A Guarda', 'A Guarda', true),
  ('1.10', 'La mar', '36780 A Guarda, Pontevedra', 'A Guarda', 'A Guarda', true),
  ('1.11', 'Casa Kokoro', 'Camiño do Suárez, 3, 36770 Portecelo, Pontevedra', 'A Guarda', 'A Guarda', true),
  ('1.12', 'Apartamentos Lof peregrinos A estivada', 'Estrada do Cruceiro, 11, 36770 Portecelo, Pontevedra', 'A Guarda', 'A Guarda', true),
  ('1.13', 'Casa Alicia', '36770 San Xián, Pontevedra', 'A Guarda', 'A Guarda', true),
  ('1.14', 'Casa Tara', 'Camiño Casetas, 36794 Oia, Pontevedra', 'A Guarda', 'A Guarda', true),
  ('2.01', 'Aloxamento A Mariña', 'Estrada Vista Alegre, 35, 36794 A Mariña, Pontevedra', 'OIA', 'Oia', true),
  ('2.02', 'Atlantic - Sea Front', '36794 Oya, Pontevedra', 'OIA', 'Oia', true),
  ('2.03', 'Casa Carola', 'Chavella, 36794 Oia, Pontevedra', 'OIA', 'Oia', true),
  ('2.04', 'Alojamiento Chavella', 'Chavella, 36794 Oia, Pontevedra', 'OIA', 'Oia', true),
  ('2.05', 'Casa La Capitana', 'Rúa Vista Alegre, 99, O Arrabal, 36794 Oia, Pontevedra', 'OIA', 'Oia', true),
  ('2.06', 'Casa Picota', 'Rúa da Palma, 11, O Arrabal, 36794 Oia, Pontevedra', 'OIA', 'Oia', true),
  ('2.07', 'Casa Puertas', 'Rúa Vicente López, 7, O Arrabal, 36794 Santa Maria De Oia, Pontevedra', 'OIA', 'Oia', true),
  ('2.08', 'Hotel A Raíña', 'Camiño do Fial, 20, 36794 Oia, Pontevedra', 'OIA', 'Oia', true),
  ('2.09', 'O refuxio do mar', 'Camiño da fonte, num.5, 36794 A Riña, Pontevedra', 'OIA', 'Oia', true),
  ('2.10', 'Casa Toñi', 'Estrada Xeral, 23, Pontevedra', 'OIA', 'Oia', true),
  ('2.11', 'Casa Máxica de Oia', 'Camino do Morouzo, 2, 36309 Pedornes, Pontevedra', 'OIA', 'Oia', true),
  ('2.12', 'Casa Porto dos Barcos', 'Estrada Xeral, 95, 36309 Pedornes, Pontevedra', 'OIA', 'Oia', true),
  ('2.13', 'Hotel Glasgow', 'Estrada Baiona a guarda Nº9, 36309 Oia, Pontevedra', 'OIA', 'Oia', true),
  ('2.14', 'Alojamiento Camino Portugués Oia', 'Rua, O Serrallo, 12, 36309 Viladesuso, Pontevedra', 'OIA', 'Oia', true),
  ('2.15', 'Albergue da Estrela', 'Estrada Vella, O Serrallo, 2, 36309 Viladesuso, Pontevedra', 'OIA', 'Oia', true),
  ('2.16', 'Hotel Costa Verde', 'O Serrallo, 51, 36309 Oia, Pontevedra', 'OIA', 'Oia', true),
  ('2.17', 'Casa Ángel 1982', '36309 Escalinata, 180, 36309 Viladesuso, Pontevedra', 'OIA', 'Oia', true),
  ('2.18', 'A casa de Florinda', 'Mougás, Oya, Pontevedra', 'OIA', 'Oia', true),
  ('2.19', 'A de Bego', 'Camiño de Lourido, 29, 36794 Oia, Pontevedra', 'OIA', 'Oia', true),
  ('2.20', 'Albergue Aguncheiro', 'Camino do Aguncheiro, 14, 36309 Mougás, Pontevedra', 'OIA', 'Oia', true),
  ('2.21', 'Camping O Muiño', 'Carretera Baiona - A Garda, Km 26, 36309 Mougás, Oia, Pontevedra', 'OIA', 'Oia', true),
  ('2.22', 'Camping Mougás', 'PO-552, 20, 36309, Pontevedra', 'OIA', 'Oia', true),
  ('2.23', 'Talaso Atlántico Spa', 'Lugar As Mariñas Mougás, 36309 Oia, Pontevedra', 'OIA', 'Oia', true),
  ('2.24', 'Hotel Faro Silleiro', 'Ctra. Faro Silleiro, 36309 Baiona, Pontevedra', 'OIA', 'Oia', true),
  ('2.25', 'Glamping do mar', 'Camiño da Cela, C.P: 36.309, Cela Vella, 36309 Baredo, Pontevedra', 'OIA', 'Oia', true),
  ('3.01', 'Hotel Rompeolas', 'Av. Joselín, 8, 36300 Baiona, Pontevedra', 'BAIONA NIGRAN', 'Baiona', true),
  ('3.02', 'Albergue Estela do Mar', 'R. Laureano Salgado, 15, 36300 Baiona, Pontevedra', 'BAIONA NIGRAN', 'Baiona', true),
  ('3.03', 'Pensión O Escondidiño', 'Camiño Río da Veiga, 6, 36300 Baiona, Pontevedra', 'BAIONA NIGRAN', 'Baiona', true),
  ('3.04', 'Apartamentos Vila do Mar', 'Lugar Covaterreña, 34, 36300 Baiona, Pontevedra', 'BAIONA NIGRAN', 'Baiona', true),
  ('3.05', 'Albergue Baionamar', 'R. Venezuela, 6, bajo 3, 36300 Baiona, Pontevedra', 'BAIONA NIGRAN', 'Baiona', true),
  ('3.06', 'Hotel Carabela La Pinta', 'Camino Entrehuertas,21-1º Esquina calle Carabela la Pinta, 36300 Baiona, Pontevedra', 'BAIONA NIGRAN', 'Baiona', true),
  ('3.07', 'Holibai', 'Av. Ramón y Cajal, 11, 36300 Baiona, Pontevedra', 'BAIONA NIGRAN', 'Baiona', true),
  ('3.08', 'Parador de Baiona', 'Av. Arquitecto Jesús Valverde, 3, 36300 Baiona, Pontevedra', 'BAIONA NIGRAN', 'Baiona', true),
  ('3.09', 'Hotel Pinzón', 'Rúa Elduayen, 21, 36300 Baiona, Pontevedra', 'BAIONA NIGRAN', 'Baiona', true),
  ('3.10', 'Hotel Anunciada', 'Rúa Ventura Misa, 58, 36300 Baiona, Pontevedra', 'BAIONA NIGRAN', 'Baiona', true),
  ('3.11', 'Hotel Baiona', 'Rúa do Conde, 36, 36300 Baiona, Pontevedra', 'BAIONA NIGRAN', 'Baiona', true),
  ('3.12', 'Pensión Mosquito', 'Rúa Ventura Misa, 58, 36300 Baiona, Pontevedra', 'BAIONA NIGRAN', 'Baiona', true),
  ('3.13', 'Hotel Pazo de Mendoza', 'Rúa Elduayen, 1, 36300 Baiona, Pontevedra', 'BAIONA NIGRAN', 'Baiona', true),
  ('3.14', 'Hotel Cais', 'Rúa Alférez Barreiro, 3, 36300 Baiona, Pontevedra', 'BAIONA NIGRAN', 'Baiona', true),
  ('3.15', 'Arribada by Estela', 'Av. Monterreal, 11, 36300 Baiona, Pontevedra', 'BAIONA NIGRAN', 'Baiona', true),
  ('3.16', 'Hostal Santa Marta Playa', 'Est. de Santa Marta, 6, 36300 Baiona, Pontevedra', 'BAIONA NIGRAN', 'Baiona', true),
  ('3.17', 'Hotel Bahía Baiona', 'Est. de Santa Marta, 13, 36308 Baiona, Pontevedra', 'BAIONA NIGRAN', 'Baiona', true),
  ('3.18', 'Albergue Playa de Sabarís', 'Rúa Porta do Sol, 55, 36393 Baiona, Pontevedra', 'BAIONA NIGRAN', 'Baiona', true),
  ('3.19', 'Hotel Vasco da Gama', 'Av. José Pereira Troncoso, 18, 36393 Baiona, Pontevedra', 'BAIONA NIGRAN', 'Baiona', true),
  ('3.20', 'Hotel Arce Baiona', 'Rúa Julián Valverde, 40, 36393 Baiona, Pontevedra', 'BAIONA NIGRAN', 'Baiona', true),
  ('3.21', 'Hotel Avenida Baiona', 'Rúa Julián Valverde, 41, 36393 Baiona, Pontevedra', 'BAIONA NIGRAN', 'Baiona', true),
  ('3.22', 'Pazo de Pías', 'Rúa Damas Apostólicas, 21, 36370 Nigrán, Pontevedra', 'BAIONA NIGRAN', 'Nigrán', true),
  ('3.23', 'Hotel Miramar Playa América', 'Carretera por la Costa Vigo - Baiona, Km 14.700, 36350 Nigrán, Pontevedra', 'BAIONA NIGRAN', 'Nigrán', true),
  ('3.24', 'Hotel Holiday', 'Estrada Pola Vía, 17, 36350 Nigrán, Pontevedra', 'BAIONA NIGRAN', 'Nigrán', true),
  ('3.25', 'O Retiro', 'Rúa Telleira, 10, 36350 Nigrán, Pontevedra', 'BAIONA NIGRAN', 'Nigrán', true),
  ('3.26', 'Hotel Val Convention', 'Rúa Rosalía de Castro, 6, Bajo, 36350 Nigrán, Pontevedra', 'BAIONA NIGRAN', 'Nigrán', true),
  ('3.27', 'Pensión Venus', 'Rúa Reverendo Jose Maria Perez Alonso, 1, 36350 Nigrán, Pontevedra', 'BAIONA NIGRAN', 'Nigrán', true),
  ('3.28', 'Pensión Residencia La Chica', 'Rúa Tomás Mirambell, 65, 36340 Nigrán, Pontevedra', 'BAIONA NIGRAN', 'Nigrán', true),
  ('3.29', 'Patos Beach House', 'Rúa Tomás Mirambell, 136, 36340 Nigrán, Pontevedra', 'BAIONA NIGRAN', 'Nigrán', true),
  ('3.30', 'Apartamentos Orinoco', 'Av. Pablo Iglesias, 2a, 36391 Nigrán, Pontevedra', 'BAIONA NIGRAN', 'Nigrán', true),
  ('3.31', 'Albergue Peregrinos San Xurxo', 'Rúa da Eira Vella, 4, 36392 Vigo, Pontevedra', 'BAIONA NIGRAN', 'Nigrán', true),
  ('4.01', 'Pensión Lucerna', 'Estrada do Vao, 130, 36331 Vigo, Pontevedra', 'VIGO', 'Vigo', true),
  ('4.02', 'Hotel Playa Samil Vigo', 'Av. Samil, 95, 36212 Vigo, Pontevedra', 'VIGO', 'Vigo', true),
  ('4.03', 'Hotel Attica 21', 'Av. Samil, 15, 36212 Vigo, Pontevedra', 'VIGO', 'Vigo', true),
  ('4.04', 'Hotel Playa Santa Baia', 'Av. da Atlántida, 121, 36208 Vigo, Pontevedra', 'VIGO', 'Vigo', true),
  ('4.05', 'Pazo Los Escudos', 'Av. da Atlántida, 106, 36208 Vigo, Pontevedra', 'VIGO', 'Vigo', true),
  ('4.06', 'Hotel Coia', 'Rúa de Sanxenxo, 1, Coia, 36209 Vigo, Pontevedra', 'VIGO', 'Vigo', true),
  ('4.07', 'Hotel Chipen', 'Av. da Florida, 12, Coia, 36210 Vigo, Pontevedra', 'VIGO', 'Vigo', true),
  ('4.08', 'Hostal Agra', 'Praza Eugenio Fadrique, 1, Freixeiro, 36208 Vigo, Pontevedra', 'VIGO', 'Vigo', true),
  ('4.09', 'Hotel Eurostars Mar de Vigo', 'Av. da Beiramar, 57, 59, 36202 Vigo, Pontevedra', 'VIGO', 'Vigo', true),
  ('4.10', 'Chocolatería Ocumare (Consigna Albergue Público de Vigo)', 'Rúa da Ribeira do Berbés, 33, 36202 Vigo, Pontevedra', 'VIGO', 'Vigo', true),
  ('4.11', 'Hostal Real Vigo', 'Rúa Real, 22, 36202 Vigo, Pontevedra', 'VIGO', 'Vigo', true),
  ('4.12', 'R4 Vigo Hostel', 'Rúa Real, 4, 36202 Vigo, Pontevedra', 'VIGO', 'Vigo', true),
  ('4.13', 'Hostal La Colegiata', 'Praza da iglesia, 3, 36202 Vigo, Pontevedra', 'VIGO', 'Vigo', true),
  ('4.14', 'Hotel Alda Porta do Sol', 'Praza Porta do Sol, 14, 36202 Vigo, Pontevedra', 'VIGO', 'Vigo', true),
  ('4.15', 'Hotel Bahía de Vigo', 'Rúa Cánovas del Castillo, 24, 36202 Vigo, Pontevedra', 'VIGO', 'Vigo', true),
  ('4.16', 'AC Hotel Palacio Universal', 'Rúa Cánovas del Castillo, 28, 36202 Vigo, Pontevedra', 'VIGO', 'Vigo', true),
  ('4.17', 'Hotel Ciudad de Vigo', 'R. de Concepción Arenal, 5, 36201 Vigo, Pontevedra', 'VIGO', 'Vigo', true),
  ('4.18', 'Hotel del Mar', 'R. de Luis Taboada, 34,
36201 Vigo, Pontevedra', 'VIGO', 'Vigo', true),
  ('4.19', 'Hotel Náutico', 'R. de Luis Taboada, 28, 36201 Vigo, Pontevedra', 'VIGO', 'Vigo', true),
  ('4.20', 'Hotel Compostela', 'Rúa García Olloqui, 5, 36201 Vigo, Pontevedra', 'VIGO', 'Vigo', true),
  ('4.21', 'Gran Hotel Nagari', 'Praza de Compostela, 21, 36201 Vigo, Pontevedra', 'VIGO', 'Vigo', true),
  ('4.22', 'Hotal Buenos Aires', 'R. de Rosalía de Castro, 6, Santiago de Vigo, 36201 Vigo, Pontevedra', 'VIGO', 'Vigo', true),
  ('4.23', 'Hotel Atlántico Vigo', 'R. de García Barbón, 35, Santiago de Vigo, 36201 Vigo, Pontevedra', 'VIGO', 'Vigo', true),
  ('4.24', 'Hotel NH Collection Vigo', 'R. de García Barbón, 17-19, Santiago de Vigo, 36201 Vigo, Pontevedra', 'VIGO', 'Vigo', true),
  ('4.25', 'Hotel Junquera', 'R. do Uruguai, 19, 21, Santiago de Vigo, 36201 Vigo, Pontevedra', 'VIGO', 'Vigo', true),
  ('4.26', 'Hostal Ancla Dorada', 'Rúa dos Irmandiños, 2, Santiago de Vigo, 36201 Vigo, Pontevedra', 'VIGO', 'Vigo', true),
  ('4.27', 'W14 Hostales', 'Rúa Martín Códax, 5, Santiago de Vigo, 36201 Vigo, Pontevedra', 'VIGO', 'Vigo', true),
  ('4.28', 'Hotel Zenit Vigo', 'Av. da Gran Vía, 1, Santiago de Vigo, 36204 Vigo, Pontevedra', 'VIGO', 'Vigo', true),
  ('4.29', 'Hotel Arsus', 'Rúa Lepanto, 8, Santiago de Vigo, 36201 Vigo, Pontevedra', 'VIGO', 'Vigo', true),
  ('4.30', 'Hotel Ogalia', 'Rúa Lepanto, 10, Santiago de Vigo, 36201 Vigo, Pontevedra', 'VIGO', 'Vigo', true),
  ('4.31', 'AGUA DE MAR Hotel Boutique', 'Rúa Lepanto, 12, Santiago de Vigo, 36201 Vigo, Pontevedra', 'VIGO', 'Vigo', true),
  ('4.32', 'Hotel Panton', 'Rúa Lepanto, 18, Santiago de Vigo, 36201 Vigo, Pontevedra', 'VIGO', 'Vigo', true),
  ('4.33', 'Hotel Lino', 'Rúa Lepanto, 26, Santiago de Vigo, 36201 Vigo, Pontevedra', 'VIGO', 'Vigo', true),
  ('4.34', 'Hotel Alda Estación Vigo', 'Rúa de Alfonso XIII, 17, Santiago de Vigo, 36201 Vigo, Pontevedra', 'VIGO', 'Vigo', true),
  ('4.35', 'B&B HOTEL Vigo', 'Rúa de Alfonso XIII, 11, Santiago de Vigo, 36201 Vigo, Pontevedra', 'VIGO', 'Vigo', true),
  ('4.36', 'Hotel Silken Axis Vigo', 'Rúa de María Berdiales, 22, Santiago de Vigo, 36203 Vigo, Pontevedra', 'VIGO', 'Vigo', true),
  ('4.37', 'Hotel Vigo Plaza', 'R. do Progreso, 13, Santiago de Vigo, 36202 Vigo, Pontevedra', 'VIGO', 'Vigo', true),
  ('4.38', 'Hotel Vigo Los Galeones Affiliated by Meliá', 'Av. de Madrid, 21, Sárdoma, 36204 Vigo, Pontevedra', 'VIGO', 'Vigo', true),
  ('4.39', 'Vigo Beds and Rooms', 'Rúa Emilia Pardo Bazán, 12, Sárdoma, 36204 Vigo, Pontevedra', 'VIGO', 'Vigo', true),
  ('4.40', 'Hostal Los Tres Países', 'Rúa de Venezuela, 61, BAJO, Santiago de Vigo, 36204 Vigo, Pontevedra', 'VIGO', 'Vigo', true),
  ('4.41', 'Sercotel Tres Luces', 'Rúa Cuba, 19, Santiago de Vigo, 36204 Vigo, Pontevedra', 'VIGO', 'Vigo', true),
  ('4.42', 'Hotel Celta', 'R. México, 22, Santiago de Vigo, 36204 Vigo, Pontevedra', 'VIGO', 'Vigo', true),
  ('4.43', 'Hotel Casablanca', 'R. México, 7, Santiago de Vigo, 36204 Vigo, Pontevedra', 'VIGO', 'Vigo', true),
  ('4.44', 'Hotel Exe Vigo', 'Rúa de Urzáiz, 76, Santiago de Vigo, 36204 Vigo, Pontevedra', 'VIGO', 'Vigo', true),
  ('4.45', 'Hotel Ipanema', 'Rúa Vázquez Varela, 31, 33, Santiago de Vigo, 36204 Vigo, Pontevedra', 'VIGO', 'Vigo', true),
  ('4.46', 'Hotel Solpor', 'Rúa Vía Nte., 9, 1º, Santiago de Vigo, 36206 Vigo, Pontevedra', 'VIGO', 'Vigo', true),
  ('4.47', 'Hotel Occidental Vigo', 'Rúa Vía Nte., 10, Santiago de Vigo, 36204 Vigo, Pontevedra', 'VIGO', 'Vigo', true),
  ('4.48', 'Hotel O Pazo', 'Rúa Campos, 11, 36213 Vigo, Pontevedra', 'VIGO', 'Vigo', true),
  ('5.01', 'Hospedaje Bahía de San Simon', 'Rúa Subida á Estación Vella, 35, 2º, 36800 Redondela, Pontevedra', 'Redondela', 'Redondela', true),
  ('5.02', 'Café Royal Picasso (consigna)', 'Rúa das Cardosas, 2, 36800 Redondela, Pontevedra', 'Redondela', 'Redondela', true),
  ('5.03', 'Albergue A Rotonda', 'Rúa Rabadeira Canabal, 1, 36800 Redondela, Pontevedra', 'Redondela', 'Redondela', true),
  ('5.04', 'Albergue Santiago de Vilavella - Redondela', 'Rúa Pai Crespo, 55, 36800 Redondela, Pontevedra', 'Redondela', 'Redondela', true),
  ('5.05', 'Albergue A Conserveira', 'Rúa Pai Crespo, 60, 36800 Redondela, Pontevedra', 'Redondela', 'Redondela', true),
  ('5.06', 'Don Vinarius Vinos y Tapas
(consigna)', 'Praza de Ponteareas, 2, Bajo, 36800 Redondela, Pontevedra', 'Redondela', 'Redondela', true),
  ('5.07', 'Cafetaría Farola
(consigna)', 'Praza de Ribadavia, 3, 36800 Redondela, Pontevedra', 'Redondela', 'Redondela', true),
  ('5.08', 'Pensión Rúa do Medio', 'Rúa Reveriano Soutullo, 42, 36800 Redondela, Pontevedra', 'Redondela', 'Redondela', true),
  ('5.09', 'Albergue Alfonso XII', 'Rúa Alfonso XII, 24, 36800 Redondela, Pontevedra', 'Redondela', 'Redondela', true),
  ('5.10', 'A Boa Estrela Pension', 'Rúa Isidoro Queimaliños, 44, 36800 Redondela, Pontevedra', 'Redondela', 'Redondela', true),
  ('5.11', 'Albergue Santiago de Redondela', 'Rúa Telmo Bernárdez, 15, 36800 Redondela, Pontevedra', 'Redondela', 'Redondela', true),
  ('5.11b', 'Apartamento O Cruceiro', 'R. Cruceiro, 28, 36800 Redondela, Pontevedra', 'Redondela', 'Redondela', true),
  ('5.12', 'El Descanso del Viajero', 'Rúa da Laxe, 36800 Redondela, Pontevedra', 'Redondela', 'Redondela', true),
  ('5.13', 'Camiño da Prata', 'Rúa Prata, 68, 36800 Redondela, Pontevedra', 'Redondela', 'Redondela', true),
  ('5.14', 'Hostel Albergue Avoa Regina Redondela', 'Rúa da Picota, 23, 36800 Redondela, Pontevedra', 'Redondela', 'Redondela', true),
  ('5.15', 'Casa da Esfarrapada', 'Rúa Espírito Santo, 23, 36800 Redondela, Pontevedra', 'Redondela', 'Redondela', true),
  ('5.16', 'A Marisma Hostal', 'Av. de Ernestina Otero, 45, 36800 Redondela, Pontevedra', 'Redondela', 'Redondela', true),
  ('5.17', 'Apartamentos Redondela-A Casa da praia', 'Camiño Dos Eidos de San Pedro, 34, 1º - duplex, 36693 Redondela, Pontevedra', 'Redondela', 'Redondela', true),
  ('5.18', 'House Capitán Nemo A', 'Estrada Catapeixes, 39, 36693 Redondela, Pontevedra', 'Redondela', 'Redondela', true),
  ('5.19', 'A Dársena do Francés', 'Estrada de Zacande, 2, 36693 Redondela, Pontevedra', 'Redondela', 'Redondela', true),
  ('5.20', 'Casa Vol', 'Rúa Carballiño, 78, 36693 Redondela, Pontevedra', 'Redondela', 'Redondela', true),
  ('5.21', 'Hotel Antolín', 'Paseo da Praia, 56, 36693 Redondela, Pontevedra', 'Redondela', 'Redondela', true),
  ('5.22', 'Pensión O Regato', 'Paseo da Praia, 9, 36693 Redondela, Pontevedra', 'Redondela', 'Redondela', true),
  ('5.23', 'O Refuxio de la Jerezana', 'Estrada do Pereiro, 43, 36693 Redondela, Pontevedra', 'Redondela', 'Redondela', true),
  ('5.24', 'Jumboli', 'Estrada Cesantes, 13, 36693 Redondela, Pontevedra', 'Redondela', 'Redondela', true),
  ('5.25', 'Casa D’Mina', 'Camino Da Tomada, 9, 36693 Redondela, Pontevedra', 'Redondela', 'Redondela', true),
  ('5.26', 'AS CHIVAS Casa Rural', 'Camiño de Saramagoso, 34, 36810 Redondela, Pontevedra', 'Redondela', 'Redondela', true),
  ('5.27', 'Villa Blas', 'Estrada da Aldea, 25, 36810 Soutoxuste, Pontevedra', 'Redondela', 'Redondela', true),
  ('5.28', 'Hostal Chocolate y Menta', 'N-550, 9, Km 34, 36810 Redondela, Pontevedra', 'Redondela', 'Redondela', true),
  ('5.29', 'Albergue A Xesteira', 'Av. Castelao, 146, 36690, Pontevedra', 'Arcade', 'Arcade', true),
  ('5.30', 'Albergue A Filla do Mar', 'N-550, 142, 36690 Arcade, Pontevedra', 'Arcade', 'Arcade', true),
  ('5.31', 'Albergue Casa Calvar', 'Lugar campo da feira Arcade, Estrada de Soutomaior, 1, 36690 Pontevedra', 'Arcade', 'Arcade', true),
  ('5.32', 'Hotel Duarte', 'Rua das Lameiriñas, 8, 36690 Arcade de Riba, Pontevedra', 'Arcade', 'Arcade', true),
  ('5.33', 'Albergue Lameiriñas', 'Rua das Lameiriñas, 8, 36690 Arcade de Riba, Pontevedra', 'Arcade', 'Arcade', true),
  ('5.34', 'Albergue Camino de Santiago O Lar de Pepa', 'Camiño Ribeiro, 1, 36691 Soutomaior, Pontevedra', 'Arcade', 'Arcade', true),
  ('5.35', 'Hotel Restaurante GBC Isape', 'Estrada de Soutomaior, 36, 36690 Soutomaior, Pontevedra', 'Arcade', 'Arcade', true),
  ('5.36', 'GES SEGUROS ARCADE
(consigna)', 'Av. Xosé Solla, 34, Bajo, 36690 Arcade, Pontevedra', 'Arcade', 'Arcade', true),
  ('5.37', 'J&C Arcade', 'Rúa Rosalía de Castro, 26, 36690 ARCADE, Pontevedra', 'Arcade', 'Arcade', true),
  ('5.38', 'HOTEL GBC ARCADE', 'Av. Castelao, 36690, Pontevedra', 'Arcade', 'Arcade', true),
  ('5.39', 'CASA HEROES DE PUENTE SAMPAYO', 'Lugar Puente-Pontesampaio, 12, 36690 A Ponte, Pontevedra', 'Pontesampaio', 'Pontesampaio', true),
  ('5.40', 'Hostel Albergue O Mesón de Ponte Sampaio', 'O Mesón, 12, 36690 Pontevedra', 'Pontesampaio', 'Pontesampaio', true),
  ('5.41', 'Hotel San Luis', 'Lugar Paredes, 35, 36141 Vilaboa, Pontevedra', 'Pontesampaio', 'Pontesampaio', true),
  ('6.01', 'Hostal Peregrino', 'Rúa de Ramón Otero Pedraio, 8, 36004 Pontevedra', 'Pontevedra', 'Pontevedra', true),
  ('6.02', 'Albergue GBC Pontevedra', 'Rúa do Gorgullón, 72, 72, 36003 Pontevedra', 'Pontevedra', 'Pontevedra', true),
  ('6.03', 'Albergue de Peregrinos Aloxa', 'Rúa do Gorgullón, 68, 36003 Pontevedra', 'Pontevedra', 'Pontevedra', true),
  ('6.04', 'Hotel Alda Estación Pontevedra', 'Rúa Eduardo Pondal, 76, 36002 Pontevedra', 'Pontevedra', 'Pontevedra', true),
  ('6.05', 'Dpaso, Urban Hostel', 'Rúa do Gorgullón, nº 16, 36003 Pontevedra', 'Pontevedra', 'Pontevedra', true),
  ('6.07', 'Nacama Hostel', 'Rúa das Lavandeiras, nº1, local 3, esquina, 36003 Pontevedra', 'Pontevedra', 'Pontevedra', true),
  ('6.08', 'Hotel Room Pontevedra', 'Rúa Profesor Filgueira Valverde, 10, 36003 Pontevedra', 'Pontevedra', 'Pontevedra', true),
  ('6.09', 'Hotel Virgen del Camino', 'Rúa da Virxe do Camiño, 55, 36001 Pontevedra', 'Pontevedra', 'Pontevedra', true),
  ('6.10', 'Hotel Galicia Palace', 'Av. de Vigo, 3, 36003 Pontevedra', 'Pontevedra', 'Pontevedra', true),
  ('6.11', 'Hotel Madrid', 'Rúa Andrés Mellado, 5, 36001 Pontevedra', 'Pontevedra', 'Pontevedra', true),
  ('6.12', 'Bulezen Urban Hostel', 'Rúa García Camba, 12, 1º PISO, 36001 Pontevedra', 'Pontevedra', 'Pontevedra', true),
  ('6.13', 'Hotel Rías Bajas', 'Rúa Daniel de la Sota Valdecilla, 7, 36001 Pontevedra', 'Pontevedra', 'Pontevedra', true),
  ('6.14', 'Hotel Alda Centro Pontevedra', 'Rúa Augusto González Besada, 5, 36001 Pontevedra', 'Pontevedra', 'Pontevedra', true),
  ('6.15', 'Hotel Apartamentos Dabarca', 'Calle de los Palamios, 6, 36001 Pontevedra', 'Pontevedra', 'Pontevedra', true),
  ('6.16', 'ACOLÁ hostel', 'Rúa Arcebispo Malvar, 15, 36002 Pontevedra', 'Pontevedra', 'Pontevedra', true),
  ('6.17', 'Acolá Sport', 'Rúa Arcebispo Malvar, 11-9, 36002 Pontevedra', 'Pontevedra', 'Pontevedra', true),
  ('6.18', 'Acolá Rooms', 'Calle Herreros, 22, 36002 Pontevedra', 'Pontevedra', 'Pontevedra', true),
  ('6.19', 'Casa Maruxa', 'Av. Santa María, 12, 36002 Pontevedra', 'Pontevedra', 'Pontevedra', true),
  ('6.20', 'Slow City Hostel', 'nº 1º Izda, Rúa Amargura, 5, 36002 Pontevedra', 'Pontevedra', 'Pontevedra', true),
  ('6.21', 'MORC-beds rooms', 'Pontevedra, 36002 Pontevedra', 'Pontevedra', 'Pontevedra', true),
  ('6.22', 'HOSTEL CHARINO', 'Rúa Paio Gómez Charino, 19, 36002 Pontevedra', 'Pontevedra', 'Pontevedra', true),
  ('6.23', 'Parador de Pontevedra', 'Rúa do Barón, 19, 36002 Pontevedra', 'Pontevedra', 'Pontevedra', true),
  ('6.24', 'Turoqua hostel', 'Rúa Sarmiento, 7, 36002 Pontevedra', 'Pontevedra', 'Pontevedra', true),
  ('6.25', 'Hotel Restaurante Rúas', 'Rúa Sarmiento, 20, 36002 Pontevedra', 'Pontevedra', 'Pontevedra', true),
  ('6.26', 'Pensión Santa Clara', 'Rúa Santa Clara, 31, 36002 Pontevedra', 'Pontevedra', 'Pontevedra', true),
  ('6.27', 'Hotel Corinto', 'Aldea Touceda, 27, 36157 Pontevedra', 'Pontevedra', 'Pontevedra', true),
  ('7.01', 'Albergue Portela', 'Lugar a Cancela, 21, 36692, Pontevedra', 'A Portela Briallos', 'Portela', true),
  ('7.02', 'Casa Rural Os Carballos', 'Lugar Outeiro, 26, 36194, Pontevedra', 'A Portela Briallos', 'Briallos', true),
  ('7.03', 'Lar Do Pazo', 'Lugar Porráns, 94, 36191 Porráns, Pontevedra', 'A Portela Briallos', 'Briallos', true),
  ('7.04', 'Albergue de Peregrinos de Briallos', 'EP-8102, 25, 8102, 36658 O Cruceiro, Pontevedra', 'A Portela Briallos', 'Briallos', true),
  ('8.01', 'Albergue Vintecatro', '58, 36655 Tivo, Pontevedra', 'Caldas de Reis', 'Caldas de Reis', true),
  ('8.02', 'A Senda Pensión & Bar', 'Travesía Pontevedra 2, 4, 36650 Caldas de Reis, Pontevedra', 'Caldas de Reis', 'Caldas de Reis', true),
  ('8.03', 'Albergue Alecer', 'Herrería, 50, 36650 Caldas de Reis, Pontevedra', 'Caldas de Reis', 'Caldas de Reis', true),
  ('8.04', 'Casa Herreria', 'Rúa Ferreria, 43, 36650 Caldas de Reis, Pontevedra', 'Caldas de Reis', 'Caldas de Reis', true),
  ('8.05', 'ALBERGUE A QUEIMADA HOSTEL', 'casco Urbano, HERRERIA 25-29, 36650 Caldas de Reis, Pontevedra', 'Caldas de Reis', 'Caldas de Reis', true),
  ('8.06', 'Kalidas Hostel Suites', 'Rúa Ferreria, 21, 36650 Caldas de Reis, Pontevedra', 'Caldas de Reis', 'Caldas de Reis', true),
  ('8.07', 'Albergue El Timonel', 'Rúa Ovellas, 1, 10, 36650 Caldas de Reis, Pontevedra', 'Caldas de Reis', 'Caldas de Reis', true),
  ('8.08', 'Balneario Acuña', 'Calle de la Herrería, 2, 36650 Caldas de Reis, Pontevedra', 'Caldas de Reis', 'Caldas de Reis', true),
  ('8.09', 'Pensión Río Umia', 'Rúa, Av. Pedro Mateo Sagasta, 16, 1º, 36650 Caldas de Reis, Pontevedra', 'Caldas de Reis', 'Caldas de Reis', true),
  ('8.10', 'Hotel Balneario Davila', 'Rúa de Laureano Salgado, 11, 36650 Caldas de Reis, Pontevedra', 'Caldas de Reis', 'Caldas de Reis', true),
  ('8.11', 'Albergue As pozas Termais', 'Rua Don Carlos García Bayón, 5, 36650 Caldas de Reis, Pontevedra', 'Caldas de Reis', 'Caldas de Reis', true),
  ('8.12', 'Pensión Augas Quentes', 'Edificio Sevilla, Rua Porto do Río, 10, Piso 1ºA, 36650 Caldas de Reis, Pontevedra', 'Caldas de Reis', 'Caldas de Reis', true),
  ('8.13', 'A CASA DO LATONEIRO', 'Rúa Real, 19, 36650 Caldas de Reis, Pontevedra', 'Caldas de Reis', 'Caldas de Reis', true),
  ('8.14', 'Hostal Celenis', 'Rúa Real, 20, 36650 Caldas de Reis, Pontevedra', 'Caldas de Reis', 'Caldas de Reis', true),
  ('8.15', 'Hotel Roquiño', 'Rua Fornos, 8, 36650 Caldas de Reis, Pontevedra', 'Caldas de Reis', 'Caldas de Reis', true),
  ('8.16', 'Pensión Fornos', 'Rua Fornos, 16, 3° izq, 36650 Caldas de Reis, Pontevedra', 'Caldas de Reis', 'Caldas de Reis', true),
  ('8.19', 'Alojamiento Hotelero VIA XIX', 'Calle Hornos, nº 13, 1º, 36650 Caldas de Reis, Pontevedra', 'Caldas de Reis', 'Caldas de Reis', true),
  ('8.20', 'Albergue Agarimo', 'Av. Pedro Mateo Sagasta, 48, 36650 Caldas de Reis, Pontevedra', 'Caldas de Reis', 'Caldas de Reis', true),
  ('8.21', 'Viviendas turisticas Terra de Augas', 'Rúa Xoan Fuentes Echevarría, 5, 36650 Caldas de Reis, Pontevedra', 'Caldas de Reis', 'Caldas de Reis', true),
  ('8.22', 'Pension Caldas', 'Rúa Xoan Fuentes Echevarría, 19, 36650 Caldas de Reis, Pontevedra', 'Caldas de Reis', 'Caldas de Reis', true),
  ('8.23', 'Pensión As Burgas', 'Rúa Xoan Fuentes Echevarría, 21, 4ºA, 36650 Caldas de Reis, Pontevedra', 'Caldas de Reis', 'Caldas de Reis', true),
  ('8.24', 'Grupo Arcanos
pension atenea
via romana', 'Rúa Xoan Fuentes Echevarría, 21, 36650 Caldas de Reis, Pontevedra', 'Caldas de Reis', 'Caldas de Reis', true),
  ('8.25', 'Pensión A Fonte', 'Rúa Xoan Fuentes Echevarría, 29, 36650 Caldas de Reis, Pontevedra', 'Caldas de Reis', 'Caldas de Reis', true),
  ('8.26', 'Hotel "O Cruceiro"', 'Rúa Xoan Fuentes Echevarría, 40, 36650 Caldas de Reis, Pontevedra', 'Caldas de Reis', 'Caldas de Reis', true),
  ('8.27', 'Apartamento Sarnadela', 'Rúa Xoan Fuentes Echevarría, 45, PORTAL 3 (1C, 36650 Caldas de Reis, Pontevedra', 'Caldas de Reis', 'Caldas de Reis', true),
  ('8.28', 'Hotel Sena', 'Rúa Xoan Fuentes Echevarría, 99, 36650 Caldas de Reis, Pontevedra', 'Caldas de Reis', 'Caldas de Reis', true),
  ('8.29', 'Motel Caldas', 'Bemil, s/n, 36659 Follente, Pontevedra', 'Caldas de Reis', 'Caldas de Reis', true),
  ('8.30', 'Albergue GBC Caldas', 'Rua as Silgadas, 16, A, 36650 Caldas de Reis, Pontevedra', 'Caldas de Reis', 'Caldas de Reis', true),
  ('8.31', 'Albergue Argemira', 'Rúa da Constitucion, 3, 36650 Caldas de Reis, Pontevedra', 'Caldas de Reis', 'Caldas de Reis', true),
  ('8.32', 'Martínez Rooms Pilgrims', 'Rúa da Constitucion, 6, 3°C, 36650 Caldas de Reis, Pontevedra', 'Caldas de Reis', 'Caldas de Reis', true),
  ('8.33', 'Albergue peregrinos Caldas de Reis
Urraka', '36650 Caldas de Reis, Pontevedra', 'Caldas de Reis', 'Caldas de Reis', true),
  ('8.34', 'Villa Galicia', 'Rua Gaioso, 16, 36650 Caldas de Reis, Pontevedra', 'Caldas de Reis', 'Caldas de Reis', true),
  ('8.35', 'O descanso do camiño', 'Rua Gaioso, 45, 36659 Caldas de Reis, Pontevedra', 'Caldas de Reis', 'Caldas de Reis', true),
  ('8.36', 'PENSIÓN DE PEREGRINOS LA MODERNA - CALDAS DE REIS - ALBERGUE', 'Av. Pedro Mateo Sagasta, 9, 36650 Caldas de Reis, Pontevedra', 'Caldas de Reis', 'Caldas de Reis', true),
  ('8.37', 'Hotel Lotus', 'Avenida Dolores Mosquera, 27, 36650 Caldas de Reis, Pontevedra', 'Caldas de Reis', 'Caldas de Reis', true),
  ('8.38', 'Estrella Do Camiño Hospedaje', '​​Outeiro-Bemil N6, 36650, Pontevedra', 'Caldas de Reis', 'Caldas de Reis', true),
  ('8.39', 'Albergue Albor Caldas de Reis', 'Rúa Real, nº63, 36650 Caldas de Reis, Pontevedra', 'Caldas de Reis', 'Caldas de
Reis', true),
  ('8.40', 'Hotel Pousada Real', 'Rúa Real, 58, 36650 Caldas de Reis, Pontevedra', 'Caldas de Reis', 'Caldas de
Reis', true),
  ('8.41', 'APARTAMENTOS RUA VELLA', 'Rúa Real, 62, 36650 Caldas de Reis, Pontevedra', 'Caldas de Reis', 'Caldas de
Reis', true),
  ('9.01', 'pension sevi', 'carracedo-cruceiro 32, 36659, Pontevedra', 'O Cruceiro Briallos Valga', 'O Cruceiro', true),
  ('9.02', 'Casa O Eirixo', 'Casaldeirigo, 37a, 36646 Valga, Pontevedra', 'O Cruceiro Briallos Valga', 'Valga', true),
  ('9.03', 'Casa Maral', '36645 Valga, Pontevedra', 'O Cruceiro Briallos Valga', 'Valga', true),
  ('9.04', 'Albergue de peregrinos de O Pino - Valga', 'Lugar Outeiro, 12, 36646 Valga, Pontevedra', 'O Cruceiro Briallos Valga', 'Valga', true),
  ('10.1', 'Albergue de peregrinos de Pontecesures', 'Carr. Escuelas, 8, 36640 Pontecesures, Pontevedra', 'Pontecesures', 'Pontecesures', true),
  ('10.2', 'Apartamentos A Casa Antiga do Monte - Pontecesures', 'Camiño San Xulián, 7, 36640 Pontecesures, Pontevedra', 'Pontecesures', 'Pontecesures', true),
  ('10.3', 'Apartamentos virxen do carmen 7', 'Rúa Sagasta, 5, 36640 Pontecesures, Pontevedra', 'Pontecesures', 'Pontecesures', true),
  ('10.4', 'Hotel A Casa do Río', 'Rúa Víctor García, 1, 36640 Pontecesures, Pontevedra', 'Pontecesures', 'Pontecesures', true),
  ('10.5', 'Casa do Hórreo', 'Rúa Cantillo, 10, 36640 Pontecesures, Pontevedra', 'Pontecesures', 'Pontecesures', true),
  ('10.6', 'A Casiña da Ponte', 'Ponte Aldea, 15917, A Coruña', 'Pontecesures', 'Pontecesures', true),
  ('11.1', 'Casa Rural A Casa Antiga do Monte', 'Camiño Vello, 6, 15916 Lestrobe, A Coruña', 'Padrón', 'Padrón', true),
  ('11.2', 'Albergue Camiño do Sar', 'Devesa nº 20 Lestrobe 150 m Padron, Rua Vila de Rianxo, 15981, A Coruña', 'Padrón', 'Padrón', true),
  ('11.3', 'Albergue da Meiga', 'Rúa Noirmoutier, 16, bajo izquierda, 15900 Padrón, A Coruña', 'Padrón', 'Padrón', true),
  ('11.4', 'Albergue O Pedrón Hostel & Rooms', 'Rua Vila de Rianxo, 11, 15900 Padrón, A Coruña', 'Padrón', 'Padrón', true),
  ('11.5', 'Vivienda Fermina Padron', 'Rúa Noirmoutier, 10, 15917 Padrón, A Coruña', 'Padrón', 'Padrón', true),
  ('11.6', 'VUT Sesar Padrón', 'calle, Rua Vila de Rianxo, 11, 15900 Padrón, A Coruña', 'Padrón', 'Padrón', true),
  ('11.7', 'Pension Flavia
Parrillada Flavia', 'Travesía Feira, 13, 15900 Padrón, A Coruña', 'Padrón', 'Padrón', true),
  ('11.8', 'Ecorooms Padrón', 'Rúa Travesía Campo da Feira, 19, 15900 Padrón, A Coruña', 'Padrón', 'Padrón', true),
  ('11.9', 'Hotel Corona de Padrón', 'Rúa Castelao, 23, 15900 Padrón, A Coruña', 'Padrón', 'Padrón', true),
  ('11.10', 'Albergue a barca de pedra', 'Rúa Vidal Cepeda, 6, 15900 Padrón, A Coruña', 'Padrón', 'Padrón', true),
  ('11.11', 'Albergue con encanto D''Camiño', 'Rúa Peregrinos, 4, 15900 Padrón, A Coruña', 'Padrón', 'Padrón', true),
  ('11.12', 'Hotel Monumento Pazo de Lestrove', '15916 Lestrobe, A Coruña', 'Padrón', 'Padrón', true),
  ('11.13', 'A parada do camiño', 'Pl. Manuel Rodríguez Cobián, 1, 15900 Padrón, A Coruña', 'Padrón', 'Padrón', true),
  ('11.14', 'Albergue & Rooms Murgadán', 'Rúa Corredoira da Barca, 5, 15900 Padrón, A Coruña', 'Padrón', 'Padrón', true),
  ('11.15', 'Albergue Corredoiras Padrón', 'Rúa Corredoira da Barca, 10, 15900 Padrón, A Coruña', 'Padrón', 'Padrón', true),
  ('11.16', 'Villa Galicia Padrón', 'Rúa Santo Domingo, 15900 Padrón, A Coruña', 'Padrón', 'Padrón', true),
  ('11.17', 'TERRA de Padrón', 'Rúa Rosalía de Castro, 14, 15900 Padrón, A Coruña', 'Padrón', 'Padrón', true),
  ('11.18', 'Pensión Doña Elena', 'Rúa Real, 9, 15900 Padrón, A Coruña', 'Padrón', 'Padrón', true),
  ('11.19', 'Hotel Chef Rivera', 'Rúa Enlace Parque, 7, 15900 Padrón, A Coruña', 'Padrón', 'Padrón', true),
  ('11.20', 'Pensión Jardín', 'Av. Estación, 3, 15900 Padrón, A Coruña', 'Padrón', 'Padrón', true),
  ('11.21', 'Primavera', 'Av. Estación, 18, 15917 Padrón, A Coruña', 'Padrón', 'Padrón', true),
  ('11.22', 'Hotel Rosalía', 'Maruxa Villanueva, S/N, 15900, La Coruña', 'Padrón', 'Padrón', true),
  ('11.23', 'Sleep Padron', 'Av. de Compostela, 5, 15900 Padrón, A Coruña', 'Padrón', 'Padrón', true),
  ('11.24', 'Pensión Restaurante Bar Grilo', 'Av. Camilo José Cela, 30, 15900 Padrón, A Coruña', 'Padrón', 'Padrón', true),
  ('11.25', 'Hostel & Rooms Casa Maia', 'Lugar de Pedreda, 107, 15917 Padrón, A Coruña', 'Padrón', 'Padrón', true),
  ('11.26', 'Albergue Cruces De Iria', 'Av. Camilo José Cela, nº48 1º, 15917 Iria Flavia, A Coruña', 'Padrón', 'Padrón', true),
  ('11.27', 'H.Camiño Portugués', 'N-550, 15917, A Coruña', 'Padrón', 'Padrón', true),
  ('11.28', 'Hotel Scala', 'Ctra. N-550, S/N, 15917 Padrón, A Coruña', 'Padrón', 'Padrón', true),
  ('12.1', 'O Lar de Romaris I/II', 'Aldea Romarís, 26, 15917 Padrón, A Coruña', 'Escravitude A Picaraña Teo Milladoiro', 'Escravitude', true),
  ('12.2', 'Casa Rural A Casa de Teo', 'Aldea Anteportas, 3, 15917 Padrón, A Coruña', 'Escravitude A Picaraña Teo Milladoiro', 'Escravitude', true),
  ('12.3', 'A Casa Da Meixida', 'Aldea Muiños, 25, 15980 Padrón, A Coruña', 'Escravitude A Picaraña Teo Milladoiro', 'Escravitude', true),
  ('12.4', 'O Lagar de Jesus', 'Vilar, 40 - A, 15980 A Escravitude, A Coruña', 'Escravitude A Picaraña Teo Milladoiro', 'Escravitude', true),
  ('12.5', 'Albergue Villa vieira', 'Escravitude, 31, 15980 A Escravitude, A Coruña', 'Escravitude A Picaraña Teo Milladoiro', 'Escravitude', true),
  ('12.6', 'Casa Grande da Capellanía', 'Escravitude, 3, 15980 A Rúa, A Coruña', 'Escravitude A Picaraña Teo Milladoiro', 'Escravitude', true),
  ('12.7', 'Restaurante y Pensión HK', 'Lugar, Aldea Bascuas, 90, 15980 A Angueira de Suso, A Coruña', 'Escravitude A Picaraña Teo Milladoiro', 'Escravitude', true),
  ('12.8', 'PR Pividal', 'Calle Picaraña, 10, 15980 A Picaraña, A Coruña', 'Escravitude A Picaraña Teo Milladoiro', 'A Picaraña', true),
  ('12.9', 'Pensión Rural Areal', 'Areal, 35, 15980 O Areal, A Coruña', 'Escravitude A Picaraña Teo Milladoiro', 'A Picaraña', true),
  ('12.10', 'Hotel Casa de Amigos', 'Aldea Picaraña, 23, Sala 1 Ground floor, 15980 A Picaraña, A Coruña', 'Escravitude A Picaraña Teo Milladoiro', 'A Picaraña', true),
  ('12.11', 'Pensión Glorioso II', 'Aldea Picaraña, 17, 15980 A Picaraña, A Coruña', 'Escravitude A Picaraña Teo Milladoiro', 'A Picaraña', true),
  ('12.12', 'Albergue La Calabaza del Peregrino', 'Lugar dua franco, 5, 15866 O Faramello, A Coruña', 'Escravitude A Picaraña Teo Milladoiro', 'Teo', true),
  ('12.13', 'Albergue de Peregrinos de Teo', 'Vilares de Calo, s/n, 15866 Rúa de Francos, A Coruña', 'Escravitude A Picaraña Teo Milladoiro', 'Teo', true),
  ('12.14', 'Casa Aurora', 'Tr.ª da Casalonga, 42, 1, 15866 Teo, A Coruña', 'Escravitude A Picaraña Teo Milladoiro', 'Tep', true),
  ('12.15', 'Calm Stay', 'Camiño de Texexe, 7, 15866 Teo, A Coruña', 'Escravitude A Picaraña Teo Milladoiro', 'Teo', true),
  ('12.16', 'Albergue Aldea da Pedreira', 'Aldea Pedreira, 90', 'Escravitude A Picaraña Teo Milladoiro', 'Teo', true),
  ('12.17', 'Casa do Cruceiro', 'Aldea Raíces, 118, 15895 Ames, A Coruña', 'Escravitude A Picaraña Teo Milladoiro', 'Teo', true),
  ('12.18', 'Hotel PAYRO', 'Rúa Anxeriz, 12, 15895 O Milladoiro, A Coruña', 'Escravitude A Picaraña Teo Milladoiro', 'Milladoiro', true),
  ('12.19', 'Milla Sonsuites', 'Rúa Agro da Vella, 1, 1C, 15895 O Milladoiro, A Coruña', 'Escravitude A Picaraña Teo Milladoiro', 'Milladoiro', true),
  ('12.20', 'Albergue Milladoiro', 'R.Buxo, 4, 15895 O Milladoiro, A Coruña', 'Escravitude A Picaraña Teo Milladoiro', 'Milladoiro', true),
  ('12.21', 'B&B HOTEL Santiago Milladoiro', 'Rua das Palmeiras, R.Buxo, esquina, 15895 La Coruña, A Coruña', 'Escravitude A Picaraña Teo Milladoiro', 'Milladoiro', true),
  ('13.01', 'Albergue la Estacion', 'Rúa de Xoana Nogueira, 14, 15702 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.02', 'Santiago Lockers', 'Rúa de Santiago León de Caracas, 8, 15701 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.03', 'México PR', 'R. da República Arxentina, 33, 15701 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.04', 'Hotel Windsor', 'R. da República de El Salvador, 16, 15701 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.05', 'Eurostars Gran Hotel Santiago', 'Avenida do Mestre Mateo, 27, 15706 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.06', 'Hostal Charo II', 'Av. de Vilagarcía, 2, 15706 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.07', 'Casa Diocesana Via Lucis', 'Rúa de José María Suárez Núñez, 1, 15705 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.08', 'Hotel Gelmírez', 'Rúa do Hórreo, 92, 15702 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.09', 'Hotel Herradura', 'Av. de Xoán Carlos I, 1, 15701 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.10', 'Nest Style Santiago', 'Rúa do Doutor Teixeiro, 15, 15701 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.11', 'Hotel Hórreo by Bossh! Hotels', 'Rúa do Hórreo, 40, 15702 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.12', 'Hostal Mafer', 'Rúa do Hórreo, nº 22, 2ª planta, 15702 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.13', 'Hotel Lux Santiago', 'Rúa do Doutor Teixeiro, 4, 15701 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.14', 'Hotel Universal', 'Plaza de Galicia, 2, 15706 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.15', 'Hostal Anosa Casa', 'Rúa de Entremurallas, 9, 15702 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.16', 'Compostela Hotel', 'Rúa do Hórreo, 1, 15701 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.17', 'Hostal Pensión "CENTRO"', 'Rúa da Senra, 11, 5º A, 15701 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.18', 'mundoalbergue', 'Rúa de San Clemente, 26, 15705 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.19', 'PR 25 de Julio', 'Av. de Rodrigo del Padrón, 4,
15705 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.20', 'Hotel Entrecercas', 'Ruela de Entrecercas, 11, 15705 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.21', 'Hostal Alda Catedral', 'Rúa do Franco, 22, 15702 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.22', 'Hostal Santa Cruz', 'Rúa do Vilar, 42, 15705 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.23', 'Hospedaje Ramos', 'Rúa da Raíña, 18, 15705 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.24', 'Hostal Suso', 'Rúa do Vilar, 65, 1º, 15705 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.25', 'Hotel Pazos Alba', 'Rúa do Pombal, 22, 15705 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.26', 'Hotel Gaio 7', 'Rúa Campo do Cruceiro do Gaio, 7, 15705 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.27', 'Hotel San Lorenzo', 'Rúa de San Lourenzo, 2, 15705 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.28', 'Hotel Palacio del Carmen, Autograph Collection', 'Rúa das Oblatas, S/N, 15703 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.29', 'Hostal Costa Azul', 'Rúa das Galeras, 18, 15705 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.30', 'Hostal Pumar', 'Rúa das Galeras, 28, bajo, 15705 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.31', 'Albergue Santiago KM0', 'Rúa das Carretas, 11, 15705 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.32', 'Parador de Santiago de Compostela', 'Praza do Obradoiro, 1, 15705 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.33', 'Hospedería San Martín Pinario', 'Praza da Inmaculada, 3, 15704 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.34', 'Hotel Monumento San Francisco', 'Campillo de, Costa de San Francisco, 3, 15705 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.35', 'Lemonade Santiago de Compostela', 'Rúa das Galeras, 44, 15705 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.36', 'Hotel NH Collection Santiago de Compostela', 'Av. do Burgo das Nacións, 4, 15704 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.37', 'Pensión Da Estrela', 'Pl. de San Martiño, 5, 2º, 15704 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.38', 'Albergue Azabache', 'Rúa da Acibechería, 15, 15704 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.39', 'The Last Stamp/ El Último Sello', 'Rúa do Preguntoiro, 10, 15704 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.40', 'Casa da Balconada', 'Rúa de Xelmírez, 9, 15704 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.41', 'Miradoiro de Belvís', 'Rúa das Trompas, 5, 15703 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.42', 'Albergue Seminario Menor', 'Av. de Quiroga Palacios, 2A, 15702 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.43', 'Hotel Virxe da Cerca by Pousadas de Compostela', 'Rúa da Virxe da Cerca, 27, 15703 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.44', 'Hotel Alda Bonaval', 'R. de Bonaval, 2, 15703 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.45', 'Hostal Giadas', 'Praza do Matadoiro, 2, 15703 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.46', 'Hotel A Tafona do Peregrino', 'Rúa da Virxe da Cerca, 7, 15703 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.47', 'ALBERGUE LINARES', 'Rúa das Rodas, 37, 15704 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.48', 'Hotel Costa Vella', 'Rúa da Porta da Pena, 17, 15704 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.49', 'Deniké', 'Rúa da Porta da Pena, 4, 15704 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.50', 'Hotel Altair', 'Rúa dos Loureiros, 12, 15704 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.51', 'Hotel Santa Clara', 'Rúa de Santa Clara, 12, 15704 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.52', 'Hotel Ciudad de Compostela', 'Av. de Lugo, 213, 15703 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.53', 'Albergue Santos', 'Rúa dos Concheiros, 48, bajo izquierda, 15703 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.54', 'Albergue SIXTOs no Caminho', 'Rúa da Fonte dos Concheiros, 2A, Bajos, 15703 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.55', 'Albergue La Credencial en Santiago de Compostela', 'Rúa da Fonte dos Concheiros, Nº13, 15701 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.56', 'Hotel San Lázaro', 'Rúa do Valiño, 1, 15703 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.57', 'albergue SANTO SANTIAGO', 'Rúa do Valiño, 5, 15707 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true),
  ('13.58', 'Albergue Dream in Santiago', 'Rúa de San Lázaro, 81, BAJO, 15707 Santiago de Compostela, A Coruña', 'Santiago', 'Santiago', true)
ON CONFLICT (external_code) DO UPDATE SET
  name       = EXCLUDED.name,
  address    = EXCLUDED.address,
  stage_name = EXCLUDED.stage_name,
  town       = EXCLUDED.town,
  active     = EXCLUDED.active;

-- Total: 346 accommodations upserted